### PR TITLE
better board display

### PR DESCRIPTION
**Pull request by Joker2770**
justify the board in console

### CODE REVIEW

**Comment by fffasttime** [comment]
https://github.com/fffasttime/Gmk1/blob/8b550f7c6a2f1795c000ea5f320965f70093b060/cppsrc/ConsolePrt.cpp#L61
If you add spaces only, the mouse clicks cannot be aligned.

qq 20180927191315
And I think the display is clear enough now.

**Comment by Joker2770** [comment]
But it looks a bit confusing on my computer. I don't know what someone else look like.
default
some look like this!

**Comment by fffasttime** [comment]
I guess this problem caused by console settings, try to enable  'use old version colsole'.

**Comment by Joker2770** [comment]
default
THANKS! It work well now. Then I have some ideas, but it's difficult for me to do. Could you write a program to analyze this game like lizzie.(https://github.com/featurecat/lizzie)

**Comment by fffasttime** [comment]
Use --logs=2 to enable generate a log file after a game, and you can see the winrate of each move.
It's not easy to write a GUI in a short time. So use console output instead?

**Comment by Joker2770** [comment]
Yes, I saw the log files before. But I don't know how to parse to adapt a GUI. Thanks anyway, thats all.

**Comment by fffasttime** [comment]
I will try to adapt Yixin board in later version. But I don't know how to do that now.

**Comment by Joker2770** [comment]
I think Yixin board is not as good as lizzie to show searh trees or winrate curve.

**Pull request closed without merging**
